//------------------------------------------------------------------------------
// <auto-generated>
//     This code was ported from the BogDb C++ Source Code 
//     by BogDB. Validates native AssemblyLoadContext Extension hot-reloading!
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using Xunit;
using BogDb.Core.Extension;
using BogDb.Core.Main;

namespace BogDb.Tests.Extension;

public class ExtensionManagerTests
{
    private static string GetExtensionAssemblyPath(string projectName)
    {
        var targetDirectory = new DirectoryInfo(AppContext.BaseDirectory);
        var configuration = targetDirectory.Parent?.Name ?? "Debug";
        var solutionRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", ".."));

        return Path.Combine(solutionRoot, projectName, "bin", configuration, "net9.0", $"{projectName}.dll");
    }

    [Fact]
    public void ExtensionManager_ThrowsFileNotFound_WhenDllMissing()
    {
        // Assemble
        var database = BogDb.Core.Main.BogDatabase.Open(":memory:");
        var manager = new ExtensionManager(database);

        // Act & Assert
        var ex = Assert.Throws<FileNotFoundException>(() => 
            manager.LoadExtension("C:/NonExistentPath/bogdb-missing.dll", "missing"));
            
        Assert.Contains("missing strictly at bounds", ex.Message);
        
        manager.Dispose();
        database.Dispose();
    }

    [Fact]
    public void ExtensionManager_LoadsExternalDemoAssembly_Successfully()
    {
        // Assemble
        var database = BogDb.Core.Main.BogDatabase.Open(":memory:");
        var manager = new ExtensionManager(database);

        var demoDllPath = GetExtensionAssemblyPath("BogDb.Extensions.Demo");

        // Act
        // This validates .NET 10 AssemblyLoadContext can sandbox entirely external plugins structurally
        manager.LoadExtension(demoDllPath, "httpfs");

        // Assert
        // Success is implicitly achieving this point without Exceptions
        Assert.True(true);
        
        manager.Dispose();
        database.Dispose();
    }

    [Fact]
    public void ExtensionManager_UnloadExtension_RemovesOwnedOptionsAndFileSystems()
    {
        using var database = BogDatabase.CreateInMemory();
        var manager = new ExtensionManager(database);

        manager.LoadExtension("httpfs");

        Assert.True(database.TryGetFileSystem("http", out _));
        Assert.True(database.TryGetExtensionOption("s3_region", out _));

        manager.UnloadExtension("httpfs");

        Assert.False(manager.IsLoaded("httpfs"));
        Assert.False(database.TryGetFileSystem("http", out _));
        Assert.False(database.TryGetExtensionOption("s3_region", out _));
    }
}
